---
- name: Install a webserver
  hosts: web
  become: true
  tasks:
    - name: Stop nginx right now
      ansible.builtin.service:
        name: nginx
        state: stopped

    - name: Ensure nginx is not started at boot
      ansible.builtin.service:
        name: nginx
        enabled: false

    - name: Ensure nginx is uninstalled
      ansible.builtin.package:
        name: nginx
        state: absent
        autoremove: true
