---
- hosts: db
  become: true

  vars_files:
    - ./files/password.yml

  tasks:
    - name: Create a new database with name webbappdb
      community.mysql.mysql_db:
        name: webbappdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
        config_file: ""

    - name: Create a new user for database webbappdb
      community.mysql.mysql_user:
        name: webappuser
        password: "{{ passvar }}"
        priv: "*.*:ALL"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
        config_file: ""
