---
- name: Copy md-files to deploy
  hosts: web
  become: true

  tasks:
    - name: Copy all md-files from ./files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/deploy
        owner: deploy
        group: deploy
        mode: "0644"
      with_fileglob: "./files/*.md"
