---
# tasks file for dbserver
- name: Ensure MariaDB-server is installed.
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Ensure mariadb is started at boot
  ansible.builtin.service:
    name: mariadb
    enabled: true

- name: Start mariadb right now
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Ensure requirements for mysql are installed
  ansible.builtin.package:
    name: python3-PyMySQL
    state: present

- name: Create a new database with name webbappdb
  community.mysql.mysql_db:
    name: webbappdb
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
    config_file: ""

- name: Include vaulted user passwords
  ansible.builtin.include_vars:
    file: password.yml

- name: Create a new user for database webbappdb
  community.mysql.mysql_user:
    name: webappuser
    password: "{{ passvar }}"
    priv: "*.*:ALL"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
    config_file: ""

- name: Copy all md-files from ./files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/deploy
    owner: deploy
    group: deploy
    mode: "0644"
  with_fileglob: "./files/*.md"
